### ISSUE TITLE
Re-evaluate proc macro approach

### ISSUE THREAD

**Issue by Kixunil** [Kixunil/configure_me#3]
Pros:
 * Easy to use
 * User can immediately see the struct
 * Syntax checking of type names etc by rustc
 * Possible to add other derives

Cons:
 * possibly harder to debug (can be resolved by some attribute?)
 * possibly weird man page generation (have filename in the source code?)
 * hygiene?

**Comment by Kixunil** [comment]
Any standardization that sandboxes proc macros might kill this.

**Comment by Kixunil** [comment]
I think that after cutting man page generation out from build script, this may be better, but we have to implement some kind of scanning. https://github.com/alexcrichton/proc-macro2/issues/213 may be a blocker for this.

**Comment by jaskij** [comment]
@Kixunil I've got a proposal written up for this, do you want it here or in a separate issue?

**Comment by Kixunil** [comment]
Sounds interesting, feel free to write it here! I also had an idea recently to do something similar to `prost` - they have both build script and a proc macro. My thinking was to generate the struct using build script and proceed from there using proc macro. So people who don't like build script can still use proc macro but they'll lose man page generation.

**Comment by jaskij** [comment]
# TL;DR

`#[path = "src/config.rs"] mod config` is legal in `build.rs`.

# What to do:

Add a `#[derive]` which allows for parsing, and can be used to generate what is needed in `build.rs`. And then import the mod with the config in `build.rs`.

# Example

Imagine a code structure like this:

```
 .
├──  build.rs
├──  Cargo.toml
└──  src
   ├──  app.rs
   ├──  bin
   ├──  config.rs
   ├──  main.rs
   └──  receiver.rs
```

We have a config struct which (preferably) sits alone in `config.rs`.

```rust
#[derive(::configure_me::Config)]
struct Config {
    #[cfg_optional(true), cfg_doc("Port to listen on."]
    port: u16,
    #[cfg_default(::std::Ipv4Addr::new(0, 0, 0, 0)), cfg_doc("IP address to bind to."]
    bind_addr: ::std::net::Ipv4Addr,
    #[cfg_doc("IP address to bind to."]
    tls_cert: String,
}
```

With `build.rs` like this:

```rust
use configure_me_codegen::ConfigExt;

#[path = "src/config.rs"] mod my_app_config;

fn main() {
    my_app_config::generate_configure_toml();
}
```

The `#[derive]` would take care of the parser, while `build.rs` would generate `config_spec.toml` (for consumption by external tools like `cfg_me`) like in the `README`.

```toml
[[param]]
name = "port"
type = "u16"
optional = false
doc = "Port to listen on."

[[param]]
name = "bind_addr"
type = "::std::net::Ipv4Addr" # Yes, this works and you can use your own types as well! (impl. Deserialize and ParseArg)
default = "::std::net::Ipv4Addr::new(0, 0, 0, 0)" # Rust expression that creates the value.
doc = "IP address to bind to."

[[param]]
name = "tls_cert"
type = "String"
doc = "Path to the TLS certificate. The connections will be unsecure if it isn't provided."
```

# The Downside

And it's a big one: this requires *somehow* importing the config struct in `build.rs`. Most likely through specifying a module with a path. This feels quite hacky. But it *does* work.

There is an alternative approach with moving the configs to a separate (sub)crate, but that probably has even more downsides (publishing?) than the mod approach.

# Discussion

What I'm relying on heavily is the compiler - to be precise, the fact that it will drop unused functions from resulting binaries. So, if `#[derive]` does not introduce any new data members to the struct, there should be no impact on the code.

If further separation is desired, an extension trait to be imported only in `build.rs` is an option.

As a bonus including additional outputs should be fairly trivial at that point.

# Closing thoughts

This is just an idea, here for discussion. To state the obvious, it is not intended to replace the the current `config_spec.toml`, but rather complement it, allowing defining it in code. Unless there's a good way to actually get the config struct in `build.rs`, this should be an optional extras.

All the details like API, generated names, etc, are temporary.
