### ISSUE TITLE
Toml subsections?

### ISSUE THREAD

**Issue by dr-orlovsky** [Kixunil/configure_me#40]
Sorry if I missed something, but looking in the docs I have not found possibility to use multiple configuration sections, like

```toml
[networking]
ip = "192.168.0.1"
port = 8000

[cli]
enable = true
```
