### ISSUE TITLE
Change sequence to map

### ISSUE THREAD

**Issue by Kixunil** [Kixunil/configure_me#47]
Consider changing sequence to map in specification Toml input. That means:

```toml
[[param]]
name = "foo"
type = "String"
```

would become:

```toml
[param.foo]
type = "String"
```

Alternative that makes Toml input map more directly to Rust code, catching duplicates much more early:

```toml
[field.foo]
cli = "param" # other possibilities: switch, disabled
type = "String"
```

So far I think I prefer the less verbose option, duplicate detection can be written differently.

@dr-orlovsky @romanz would appreciate your thoughts.
